parameters:
    virhi_ui_rest_api_doctrine.service.loader.class: Virhi\LazyRestApiUiBundle\UI\Service\HttpClient
    virhi_ui_rest_api_doctrine.service.menu.class: Virhi\LazyRestApiUiBundle\UI\Service\MenuService
    virhi_ui_rest_api_doctrine.service.object_structure.class: Virhi\LazyRestApiUiBundle\UI\Service\ObjectStructureService
    virhi_ui_rest_api_doctrine.service.entity.class: Virhi\LazyRestApiUiBundle\UI\Service\EntityService
    virhi_ui_rest_api_doctrine.service.dashbord.class: Virhi\LazyRestApiUiBundle\UI\Service\DashbordService

services:

    virhi_ui_rest_api_doctrine.guzzle_client:
        class: %guzzle.client.class%
        arguments: [%virhi_ui_rest_api_doctrine.api_url%]
        tags:
            -  { name: guzzle.client }

    virhi_ui_rest_api_doctrine.service.dashbord:
        class: %virhi_ui_rest_api_doctrine.service.dashbord.class%
        arguments:
            - @virhi_ui_rest_api_doctrine.service.entity
            - @virhi_ui_rest_api_doctrine.service.object_structure

    virhi_ui_rest_api_doctrine.service.menu:
        class: %virhi_ui_rest_api_doctrine.service.menu.class%
        arguments: [@virhi_ui_rest_api_doctrine.service.object_structure]

    virhi_ui_rest_api_doctrine.service.object_structure:
        class: %virhi_ui_rest_api_doctrine.service.object_structure.class%
        arguments:
            - @virhi_ui_rest_api_doctrine.service.loader
            - %virhi_ui_rest_api_doctrine.api_url%

    virhi_ui_rest_api_doctrine.service.loader:
        class: %virhi_ui_rest_api_doctrine.service.loader.class%
        arguments: [@virhi_ui_rest_api_doctrine.guzzle_client]

    virhi_ui_rest_api_doctrine.service.entity:
        class: %virhi_ui_rest_api_doctrine.service.entity.class%
        arguments:
            - @virhi_ui_rest_api_doctrine.service.loader
            - @virhi_ui_rest_api_doctrine.service.object_structure
            - %virhi_ui_rest_api_doctrine.api_url%
